### ISSUE TITLE
ImportError: libImath-3_1.so.29: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by schrmh** [rocm-arch/python-torchvision-rocm#5]
Title is the issue.

Also as a side note since no python-pytorch-rocm repo exists here: that still depends on `hipmagma`  that got replaced in Arch.

**Comment by wuxxin** [comment]
Hi, please make a reproducible description of your issue, eg. 

- what command did you use that produced that error message in relation to python-torchvision-rocm
- what command did you use to build python-torchvision-rocm
- which archlinux type you use

As for python-pytorch-rocm: I don't maintain python-pytorch-rocm, but if you want to create an issue for it, go to
https://archlinux.org/packages/community/x86_64/python-pytorch-rocm/

and click on  "Add New Bug" in the box located in the upper right.

**Comment by schrmh** [comment]
I first used paru and then m̀akepkg -si`to build and install the PKGBUILD and I'm pretty sure it showed up during the step so something in there depends on an older imath version.

I'm on Arch Linux x86_64.
Here my bash history:
```
#1679281761
sudo pacman -Syu  
#1679281766  
sudo pacman -S python-pytorch-rocm  
#1679281707  
sudo downgrade hipmagma 
#1679282000  
sudo pacman -S python-pytorch-rocm  
#1679282439  
paru python-torchvision-rocm  
#1679282538  
git clone https://aur.archlinux.org/python-torchvision-rocm.git  
#1679282545  
cd python-torchvision-rocm/  
#1679282549  
makepkg -si  
#1679283100  
sudo ccm s  
```

**Comment by wuxxin** [comment]
on my machine, the build of torchvision still works, but my imath library is still at *.so.29".

probably python-pytorch-rocm should include a dependency on imath, 
and be rebuild with the latest imath (*.so.30)

current python-pytorch-rocm build is from 2023-02-21, 
which depends on an earlier version of imath (having ".so.29")

you can look up which python libraries depend on the older imath library, by executing:

```sh
LANG=C; find /usr/lib/python3.10/ -executable -type f -o -type l | xargs -L 1 bash -c '(x=$1 ;ldd $x 2>/dev/null | grep -q -i -F "imath-3_1.so.29" && echo $x)' self
```

So because python-torchvision-rocm is build from source, it will pickup the installed version, 
meaning your error should be related to python-pytorch-rocm which is in [Community] not in AUR,
but did not get a rebuild since the imath update, which probably causes your error.

Please comment or reopen if you feel this is still related to python-torchvision-rocm
