### ISSUE TITLE
aur not build - librt.a error

### ISSUE THREAD

**Issue by nidjan** [rocm-arch/python-torchvision-rocm#8]
good day (10.apr.23)
manjaro. pamac aur build. i can't build this, because cant make target /usr/lib/x86_64-linux-gnu/librt.a
This is because glibc update from 2.33 with change of this lib.
guys on reddit say, that this lib can remove from makefile. i try this and post after.
----
i dont know how to remove librt.a from makefile, so this i add link to /usr/lib/librt.a on /usr/lib/x86_64-linux-gnu/librt.a and now build, but i have another error - 

[100%] Linking CXX shared library libtorchvision.so
/usr/bin/ld: CMakeFiles/torchvision.dir/torchvision/csrc/vision_hip.cpp.o (symbol from plugin): в функции «vision::cuda_version()»:
(.text+0x0): повторное определение «vision::cuda_version()»; CMakeFiles/torchvision.dir/torchvision/csrc/vision.cpp.o (symbol from plugin):(.text+0x0): здесь первое определение
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make[2]: *** [CMakeFiles/torchvision.dir/build.make:580: libtorchvision.so] Ошибка 1

**Comment by wuxxin** [comment]
hey, does your build error still exist ?
Have you tried with the newest pytorch and torchvision ?

**Comment by nidjan** [comment]
Yes, problem exist. I dont see in repos new torch and torchvision and now i try to build from sources pytorch-2.0.1 for opencl-amd/opencl-amd-dev 5.4.3 .

After success i want to try build torchvision from sources - but now i have problem with build pytorch %)

**Comment by wuxxin** [comment]
Hey, thank you for your quick answer.

i dont think that pytorch will work with opencl-amd, 
at least the arch package python-pytorch-rocm (currently 2.0.1-1)

- https://archlinux.org/packages/extra/x86_64/python-pytorch-rocm/

uses the ROCM stack and so does python-torchvision-rocm, because it uses hipify to translate CUDA code to ROCM code. 

I am not aware of a pytorch version build working on opencl, but ymmv.

However this package is about pytorch and torchvision on the ROCM stack, and not OPENCL.

I am closing this for now, because it is not related to ROCM.
